name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        uses: actions/checkout@v2
        run: ci/build.sh

      - name: Store docker image
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: github-actions-test-image.tar.gz
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Fetch docker image
        uses: actions/download-artifact@v2

      - name: Test
        uses: actions/checkout@v2
        run: ci/test.sh
